### ISSUE TITLE
Customers - undefined adresses colllection

### ISSUE THREAD

**Issue by der-workfloh** [allin-data/magento2-content-fuzzyfyr#1]
Using customer flags results in error with unknown adresses collection.

```
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Customer\Model\Data\Customer::getAddressesCollection() in /var/www/vendor/allindata/magento2-content-fuzzyfyr/Observer/CustomersObserver.php:84
Stack trace:
#0 /var/www/vendor/allindata/magento2-content-fuzzyfyr/Observer/CustomersObserver.php(63): AllInData\ContentFuzzyfyr\Observer\CustomersObserver->doUpdate(Object(AllInData\ContentFuzzyfyr\Model\Configuration), Object(Magento\Customer\Model\Data\Customer))
#1 /var/www/vendor/allindata/magento2-content-fuzzyfyr/Observer/FuzzyfyrObserver.php(52): AllInData\ContentFuzzyfyr\Observer\CustomersObserver->run(Object(AllInData\ContentFuzzyfyr\Model\Configuration))
#2 /var/www/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): AllInData\ContentFuzzyfyr\Observer\FuzzyfyrObserver->execute(Object(Magento\Framework\Event\Observer))
#3 /var/www/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(AllInData\ContentFuzzyfyr\Observ in /var/www/vendor/allindata/magento2-content-fuzzyfyr/Observer/CustomersObserver.php on line 84
```

**Comment by der-workfloh** [comment]
Fixed in [v1.2.0](https://github.com/allin-data/magento2-content-fuzzyfyr/releases/tag/v1.2.0)
